### ISSUE TITLE
Unknown plugin "transform-runtime"

### ISSUE THREAD

**Issue by colinStevenson** [rodzzlessa24/vue-webgulp#3]
A fresh download/ install of this project yields the following error for me: 

**stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: ModuleBuildError: Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "[project]/.babelrc" at 0, attempted to resolve relative to "[project]"**

On the yarn install, I do see the warning: 

> warning Incorrect peer dependency "babel-runtime@^5.8.0"

 but I don't see any reference to 5.8 elsewhere in the project. Any assistance would be greatly appreciated.

**Comment by threeaccents** [comment]
@colinStevenson I've made some updates to the package let me know if you are still running into issues

**Comment by colinStevenson** [comment]
Thanks @rodzzlessa24 , looks like this is all good on my end.
